import { Component, OnInit } from '@angular/core';


/*
pour l'utilisation de
import data from '../assets/mock-data/articles.json';
dans le fichier tsconfig.json sous les options du compilateur,
 nous devons ajouter les configurations ==> "resolveJsonModule": true, "esModuleInterop": true
*/

@Component({
  selector: 'app-root',                 // the content generated by the component should be inserted into the app-root element
  templateUrl: './app.component.html',  // specify the component’s template,
  styleUrls: ['./app.component.css']    // one or more CSS stylesheets that are used to style
})

export class AppComponent implements OnInit {
  title = 'Mon blog';

  // load data from file json
  // article = data;


  constructor() { // Dependency Injection
  }
  ngOnInit(){

  }
}
